import { useState } from 'react'

const SCOUT_URL = import.meta.env.VITE_SCOUT_URL
const MIN_CHARS = 80

const SAMPLE_JD = `Data Engineer — Payments Risk (Fintech, New York, hybrid)

You'll build and run the batch and near-real-time pipelines that feed our fraud and risk models.

Requirements
- 2+ years building production data pipelines in Python and SQL
- Experience with Airflow or a similar orchestrator
- Hands-on AWS (S3, Lambda, Athena or Redshift)
- Data modeling for analytics and ML features
- Experience with Spark or Kafka
- Comfortable working with analysts and data scientists to scope requirements

Nice to have
- Fraud, risk, or financial data experience
- Infrastructure as code (Terraform)`

const ERRORS = {
  rate_limited: 'Too many reports in a minute. Give it a moment and try again.',
  busy: 'The scout is busy right now. Try again in a minute.',
  too_short: 'That looks too short to be a job description. Paste the full posting.',
  too_long: 'That posting is very long. Trim it to the role and requirements and try again.',
  not_configured: 'The scout is warming up and isn’t available yet. Check back soon.',
  refused: 'The scout couldn’t write a report for that text. Try pasting just the job description.',
}

const VERDICT_TONE = { 'Strong fit': 'strong', 'Good fit': 'good', 'Partial fit': 'partial', Stretch: 'stretch' }

export default function Scout() {
  const [jd, setJd] = useState('')
  const [state, setState] = useState({ status: 'idle' })

  const run = async e => {
    e.preventDefault()
    setState({ status: 'loading' })
    try {
      const res = await fetch(`${SCOUT_URL}/scout`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jd }),
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(ERRORS[data.error] || 'Something went wrong. Please try again.')
      setState({ status: 'done', report: data.report })
    } catch (err) {
      setState({ status: 'error', message: err.message || 'Something went wrong. Please try again.' })
    }
  }

  const r = state.report
  return (
    <section id="scout">
      <div className="wrap">
        <div className="eyebrow rv">AI scouting report</div>
        <h2 className="title rv">Scout me for your role</h2>
        <p className="sub rv">Paste a job description and get an honest read on the fit: what matches, with evidence from my experience, and what doesn&apos;t.</p>

        <div className="scout rv">
          <form className="panel scout-input" onSubmit={run}>
            <label htmlFor="jd">Job description</label>
            <textarea
              id="jd"
              value={jd}
              onChange={e => setJd(e.target.value)}
              placeholder="Paste the role's responsibilities and requirements…"
              maxLength={15000}
              required
            />
            <div className="scout-actions">
              <button type="button" className="btn" onClick={() => setJd(SAMPLE_JD)}>Try a sample</button>
              <button type="submit" className="btn gold" disabled={state.status === 'loading' || jd.trim().length < MIN_CHARS}>
                {state.status === 'loading' ? 'Scouting…' : 'Run scouting report'}
              </button>
            </div>
            <p className="scout-note">Generated by Claude from my résumé and projects only; it can make mistakes. The text you paste is sent to Anthropic to write the report and isn&apos;t stored here.</p>
          </form>

          <div className="panel scout-output" aria-live="polite" aria-busy={state.status === 'loading'}>
            {state.status === 'idle' && (
              <div className="scout-empty">
                <span className="pc-crest">PP</span>
                <p>Your report appears here: verdict, matched requirements with evidence, honest gaps, and questions worth asking.</p>
              </div>
            )}
            {state.status === 'loading' && (
              <div className="scout-empty">
                <span className="scout-spinner" aria-hidden="true" />
                <p>Reviewing the role against the record…</p>
              </div>
            )}
            {state.status === 'error' && <div className="scout-empty"><p>{state.message}</p></div>}
            {state.status === 'done' && !r.is_job_description && (
              <div className="scout-empty"><p>That doesn&apos;t look like a job description. Paste a role&apos;s responsibilities and requirements to get a report.</p></div>
            )}
            {state.status === 'done' && r.is_job_description && (
              <article className="report">
                <div className="report-head">
                  <span className={`verdict v-${VERDICT_TONE[r.verdict]}`}>{r.verdict}</span>
                  <h3>{r.role_title}</h3>
                  <p>{r.headline}</p>
                </div>
                {r.matches.length > 0 && (
                  <div className="report-block">
                    <h4>Matches</h4>
                    <ul>{r.matches.map((m, i) => (
                      <li key={i} className="hit">
                        <b>{m.requirement}</b>
                        <span>{m.evidence}</span>
                        <small>{m.source}</small>
                      </li>
                    ))}</ul>
                  </div>
                )}
                {r.gaps.length > 0 && (
                  <div className="report-block">
                    <h4>Gaps</h4>
                    <ul>{r.gaps.map((g, i) => (
                      <li key={i} className="miss"><b>{g.requirement}</b><span>{g.note}</span></li>
                    ))}</ul>
                  </div>
                )}
                {r.talking_points.length > 0 && (
                  <div className="report-block">
                    <h4>Worth asking</h4>
                    <ul className="asks">{r.talking_points.map((t, i) => <li key={i}>{t}</li>)}</ul>
                  </div>
                )}
                <a className="btn gold" href="#contact">Talk to me about this role</a>
              </article>
            )}
          </div>
        </div>
      </div>
    </section>
  )
}
